services:
  authorization-service:
    path: ./authorization-service

  product-service:
    path: ./product-service

  import-service:
    path: ./import-service
    params:
      productsQueueUrl: ${product-service.productsQueueUrl}
      productsQueueArn: ${product-service.productsQueueArn}
      tokenAuthorizerArn: ${authorization-service.tokenAuthorizerArn}



