service: authorization-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  stackName: ${self:service}-${self:provider.stage}
  profile: personalAccount

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer

