service: import-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  stackName: ${self:service}-${self:provider.stage}
  profile: personalAccount
  environment:
    BUCKET_NAME: ${self:custom.bucketName}
    BUCKET_REGION: ${self:provider.region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:ListBucket
          Resource:
            - arn:aws:s3:::${self:custom.bucketName}
        - Effect: Allow
          Action: s3:*
          Resource:
            - arn:aws:s3:::${self:custom.bucketName}/*


plugins:
  - serverless-webpack
  - serverless-offline

custom:
  bucketName: import-service-bucket-${self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: /import
          method: get
          cors: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
          existing: true


